### ISSUE TITLE
country-2-codes.json: Use full name from EU publication for TW (Taiwan)

### ISSUE THREAD

**Issue by medicalwei** [ehn-dcc-development/eu-dcc-valuesets#45]
Taiwan is listed by ISO 3166 as "Taiwan, Province of China" due to the status of Taiwan inside the UN, however this puts Taiwan directly as "a province of China" in political standpoint.  As EU-DCC format is also issued from Taiwan government as well as admitting EU-DCC format from EU countries (and others adopting EU-DCC format), I would like to suggest changing it to Taiwan.

Therefore, according to [List of countries, territories and currencies from EU Interinstitutional Style Guide](http://publications.europa.eu/code/en/en-5000500.htm), the full name of TW is Taiwan.  Is it possible to adopt this standard over ISO 3166?

**Comment by dslmeinte** [comment]
@kruzikh @skounis What would be the EU's official stance on this?

**Comment by kruzikh** [comment]
Official EU stance could be be expressed only by EU itself :-) Let's put this on the agenda of the SGS, maybe through Konstantin?

**Comment by skounis** [comment]
> Official EU stance could be expressed only by EU itself :-) Let's put this on the agenda of the SGS, maybe through Konstantin?

Agree; we need to bring/raise this in one of our forthcomming calls.

**Comment by dslmeinte** [comment]
FWIW: _technically_, the change would be trivial, and essentially have 0 impact, because the `display` value of the country 2-codes is not used in any code that's actively produced and maintained by the eHN. That might be different for the reference implementations of the wallet and verifier apps by T-Systems, though.

**Comment by skounis** [comment]
@dslmeinte How is the country list maintained? I would guess it is generated by a list coming from ISO. If this is the case, and we decide to so, an exception in the process should be added.

**Comment by dslmeinte** [comment]
@skounis It's maintained in essentially the same way as the other value sets (except for `test-manf.json` which is included non-authoritatively here), so updates come from the Semantic Group in the form of updates to the guidelines document. We've made a couple of updates for Kosovo (XK) in the past. I'm guessing the initial contents was indeed copied verbatim from the ISO, as the Wikipedia page also list Taiwan as “province of China”.

**Comment by kruzikh** [comment]
The original country codes value set was originally generated from FHIR vlaue set using following code:

curl http://hl7.org/fhir/R4/valueset-iso3166-1-2.json |
jq '.compose.include[0].system as $system | .meta.lastUpdated[0:10] as $version| reduce .compose.include[0].concept[] as $i ({}; .[$i.code] =
{
    "display": $i.display,
    "lang": "en",
    "active": true,
    "system": $system,
    "version": ""
})| {"valueSetId": "country-2-codes", "valueSetDate":$version, "valueSetValues": .}' > ~/dev/GitHub/ehn-dgc-schema/valuesets/country-2-codes.json

Since then it is maintained manually.

**Comment by ryanbnl** [comment]
@kruzikh @skounis has anything happened to this?

**Comment by kruzikh** [comment]
No change as far s I know. Nobody rised this issue on SGS.

**Comment by skounis** [comment]
@kruzikh @ryanbnl Let's put it in the agenda for the next IOT meeting.

**Comment by ryanbnl** [comment]
Closing this as no changes are being made given the unclear future of the DCC. If the outlook changes it can be re-opened.
